### ISSUE TITLE
How to get Auth Key 

### ISSUE THREAD

**Issue by apurvageete** [proximiio/proximiio-android-demo#4]
How to get auth key ...Within your suggestion....!   "After that you need to replace the auth key placeholder with your own auth key (in MainActivity.java), which can be found in your portal under "Applications":

public static final String AUTH = "AUTH_KEY_HERE"; // TODO: Replace with your own!"

I cannot fid who to get this key

**Comment by SamiPatanen** [comment]
Hi!

If you haven't created an account yet, please do so at https://proximi.io/registration/.

Then, log in to your account in the portal at https://portal.proximi.io/.

In the portal, select "Applications" from the side menu, and copy the auth key of the application you wish to use. Paste it to replace the placeholder in the code.

Apologies from the late reply.

**Comment by SamiPatanen** [comment]
Closing this issue. If you have any further questions, feel free to contact support@proximi.io.
